language: cpp

sudo: required

packages:
- g++-7 scons make pkg-config build-essential libsdl2-dev

install:
- sudo make install

script:
- sm -C example/sdl2 CXX="g++-7"
- sm -C example/hello CXX="g++-7" run
