language: cpp python
sudo: yes
dist: bionic

addons:
  apt:
    update: true
    packages:
      - build-essential
      - figlet
      - freeglut3-dev
      - freeglut3-dev
      - g++-mingw-w64-x86-64
      - git
      - gtk+3-dev
      - libboost-all-dev
      - libglew-dev
      - libsdl2-dev
      - libsfml-dev
      - make
      - mesa-common-dev
      - qtbase5-dev
      - qt5-default
      - qtdeclarative5-dev
      - scons
      - python3
      - python3-pip
      - apt-utils
      - apt-file
      - libconfig++-dev
      - libconfig++
      - libopenal-dev
      - libglfw3-dev
      - libvulkan-dev
      - libboost-all-dev
      - libglm-dev
      - libsdl2-mixer-dev
      - libboost-system-dev

script:
  - sudo pip install pathlib || sudo pip3 install pathlib || true
  - make
  - sudo make install
  - python3 tests/all.py fastclean:build vulkan vulkan_glfw
