language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6 scons make pkg-config build-essential
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7 scons make pkg-config build-essential
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc pkg-config make scons && CC=gcc-7 && CXX=g++-7"

    - os: freebsd
      env:
        - MATRIX_EVAL="pkg install pkgconf gmake scons gcc"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"

script:
- if [ $TRAVIS_OS_NAME == linux ]; then make; sudo make install; sm -C examples/hello; fi
- if [ $TRAVIS_OS_NAME == osx ]; then make; sudo make install; sm -C examples/hello; fi
- if [ $TRAVIS_OS_NAME == freebsd ]; then make; sudo gmake install; sm -C examples/hello; fi
