dist: bionic
sudo: no

addons:
  apt:
    update: true
    packages:
      - build-essential
      - figlet
      - freeglut3-dev
      - freeglut3-dev
      - g++-mingw-w64-x86-64
      - git
      - gtk+3-dev
      - libboost-all-dev
      - libglew-dev
      - libsdl2-dev
      - libsfml-dev
      - make
      - mesa-common-dev
      - qtbase5-dev
      - qt5-default
      - qtdeclarative5-dev
      - scons
      - apt-utils
      - apt-file
      - libconfig++-dev
      - libconfig++
      - libopenal-dev
      - libboost-all-dev
      - libglm-dev
      - libsdl2-mixer-dev
      - libboost-system-dev

script:
  - export PATH="$PWD/usr/bin:$PATH"
  - curl -s "https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tar.xz" | tar JxC /tmp
  - pushd /tmp/Python-3.7.1
  - ./configure --prefix="/usr" 2>/dev/null 1>/dev/null
  - popd
  - DESTDIR=. make -C /tmp/Python-3.7.1 install 2>/dev/null 1>/dev/null
  - python3 --version
  - make
  - DESTDIR=. make install
  - sed -i "s,/usr/share/sakemake,$PWD/usr/share/sakemake,g" usr/bin/sakemake
  - ln -sf "$PWD/usr/bin/sakemake" usr/bin/sm
  - sm version
  - tests/all.py fastclean:build vulkan vulkan_glfw
