language: cpp

sudo: required
distro: artful

packages:
- scons make pkg-config build-essential libsdl2-dev

install:
- sudo make install

script:
- sm -C example/sdl2
- sm -C example/tinyhello small=1 run
- sm -C example/hello/common test
- sm -C example/hello run
