language: cpp

sudo: required

packages:
- scons make pkg-config build-essential

install:
- sudo make install

script:
- sm -C examples/tinyhello small=1 run
- sm -C examples/hello/common test
- sm -C examples/hello run
- sm
