services:
  - docker

language: cpp
dist: bionic
addons:
  apt:
    packages:
      - scons
      - cmake
      - ninja-build
      - g++-9

script:
  - make && sudo make install
  - cxx -C examples/hello
  - cd examples/hello && cxx clean && cxx cmake ninja && cd ../..
  - tests/ubuntu/run.sh
  - tests/arch/run.sh
