dist: bionic
sudo: no

addons:
  apt:
    update: true
    packages:
      - apt-file
      - apt-utils
      - build-essential
      - figlet
      - freeglut3-dev
      - g++-8
      - g++-mingw-w64-x86-64
      - git
      - gtk+3-dev
      - libboost-all-dev
      - libboost-system-dev
      - libconfig++
      - libconfig++-dev
      - libglew-dev
      - libglm-dev
      - libopenal-dev
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libsfml-dev
      - make
      - mesa-common-dev
      - qt5-default
      - qtbase5-dev
      - qtdeclarative5-dev
      - scons

script:
  - export ROOTDIR="$PWD"
  - export PATH="$ROOTDIR/usr/bin:$PATH"
  - export LD_LIBRARY_PATH="$ROOTDIR/usr/lib:$LD_LIBRARY_PATH"
  - export PYVER=3.7.1
  - curl -s "https://www.python.org/ftp/python/$PYVER/Python-$PYVER.tar.xz" | tar JxC /tmp
  - pushd /tmp/Python-$PYVER
  - ./configure --prefix=/usr 2>/dev/null 1>/dev/null
  - make 2>/dev/null 1>/dev/null
  - DESTDIR="$ROOTDIR" PREFIX=/usr make install 2>/dev/null 1>/dev/null
  - rm -rf /tmp/Python-$PYVER
  - python3 --version
  - popd
  - make
  - DESTDIR="$ROOTDIR" make install
  - sed -i "s,/usr/share/sakemake,$PWD/usr/share/sakemake,g" usr/bin/sakemake
  - ln -sf "$PWD/usr/bin/sakemake" usr/bin/sm
  - sm version
  - tests/all.py fastclean:build vulkan vulkan_glfw
