language: cpp

sudo: false
distro: artful

packages:
- scons make pkg-config build-essential libsdl2-dev

install:
- make

script:
- alias sm=src/sakemake
- sm -C example/sdl2
- sm -C example/hello run
- sm -C example/
