language: cpp

sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

packages:
- scons make pkg-config build-essential libsdl2-dev

install:
- sudo make install

script:
- sm -C example/sdl2 CXX=g++-7
- sm -C example/tinyhello small=1 run CXX=g++-7
- sm -C example/hello/common test CXX=g++-7
- sm -C example/hello run CXX=g++-7
