language: cpp

sudo: required

services:
  - docker

before_install:
  - docker run -t ubuntu_artful -d ubuntu:artful -v "$TRAVIS_BUILD_DIR":/root/sakemake /bin/bash -c "cd /root/sakemake; apt update; apt upgrade; apt install libsdl2-dev build-essential scons make; sudo make install"

script:
- docker exec -t ubuntu_artful /bin/bash -c "cd /root/sakemake/example; sm -C tinyhello small=1 run"
- docker exec -t ubuntu_artful /bin/bash -c "cd /root/sakemake/example; sm -C hello/common test"
- docker exec -t ubuntu_artful /bin/bash -c "cd /root/sakemake/example; sm -C hello run"
