language: cpp

#sudo: required

services:
  - docker

    #addons:
    #  apt:
    #    sources:
    #      - ubuntu-toolchain-r-test
    #    packages:
    #      - g++-8
    #
    #packages:
    #- scons make pkg-config build-essential
    #
    #install:
    #- sudo make install

script:
  #- sm -C examples/tinyhello small=1 run CXX=g++-8
  #- sm -C examples/hello/common test CXX=g++-8
  #- sm -C examples/hello run CXX=g++-8
  #- sm version
- cd tests/arch && ./run.sh
