services:
  - docker

language: cpp
dist: bionic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - scons
      - cmake
      - ninja-build

script:
  - make && sudo make install
  - cxx -C examples/hello
  - cd examples/hello && cxx clean && cxx cmake ninja && cd ../..
  - tests/ubuntu/run.sh
  - tests/arch/run.sh
