services:
  - docker

dist: bionic
addons:
  apt:
    packages:
      - python
      - scons
      - cmake
      - ninja
      - g++9

script:
  - make && sudo make install
  - cxx -C examples/hello
  - cd examples/hello && cxx clean && cxx cmake ninja
  - tests/ubuntu/run.sh
  - tests/arch/run.sh
