language: cpp

sudo: required

services:
  - docker
  - vagrant

script:
  - sm version
  - (cd tests/arch && ./run.sh)
  - (cd tests/ubuntu && ./run.sh)
  - (cd tests/void && ./run.sh)
  - (cd tests/freebsd && ./run.sh)
  - (cd tests/netbsd && ./run.sh)
